name: Go
on: [push]
jobs:
  build-cli:
    name: Build cli
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Set up zola 0.8.0
      run: |
        wget -q -O - "https://github.com/getzola/zola/releases/download/v0.8.0/zola-v0.8.0-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /usr/local/bin

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get Go dependencies
      run: |
        cd go
        go get -v -t -d ./...

    - name: Build CLI
      run: |
        cd go
        go build -v svc/client/main.go

    - name: Build static site
      env:
        CLICOLOR: 0
      run: |
        cd site
        zola build

    - name: Publish CLI
      run: |
        cd go
        echo "published CLI"

    - name: Publish static site
      run: |
        cd site
        echo "published static site"